### ISSUE TITLE
Enabling Keyboard Shortcuts

### ISSUE THREAD

**Issue by Rosti2022** [brettferdosi/goftam#2]
Hi, 

Thanks for this truly excellent tool. I have compiled it from code on Apple Silicon and it works perfectly!

My question is whether you can enable Keyboard shortcuts in the input menu, to force Right to Left typing direction in the many apps which do not have this option under the Format menu or similar. The standard Mac OS input sources have such an option, but Goftam does not appear to have it. Or else, could you kindly explain how to enable keyboard shortcuts?

Many thanks again

**Comment by brettferdosi** [comment]
Hi, I was able to get the keyboard shortcuts you're talking about working with Goftam. In Keyboard Preferences, enable both Goftam and a standard Mac OS input source that has the keyboard shortcuts you're talking about (e.g. Persian - Standard). In the configuration for the Mac OS input source, make sure the bidirectional keyboard shortcuts are enabled. Then, even when you have Goftam selected, the shortcuts will work.
